config/routes.rb
Hroniki::Application.routes.draw do

  get "subscriptions/create"

  resources :suggests
  resources :hroniks
  match '/hroniks/comment' => 'hroniks#comment', :via => :post

  resources :articles
  match '/articles/comment' => 'articles#comment', :via => :post
  
  match '/olds/issues' => 'olds#issues', :via => :get, :as => :issues
  match '/issues/:id' => 'olds#issue', :as => :issue
  resources :olds
  match '/olds/comment' => 'olds#comment', :via => :post
  
  mount Ckeditor::Engine => '/ckeditor'
  
  match '/feedbacks' => 'feedbacks#create', :via => :post, :as => :feedbacks
  match '/subscriptions' => 'subscriptions#create', :via => :post, :as => :subscriptions
  match '/feedback' => 'static_pages#feedback'
  match '/calendar' => 'events#index'
  match '/events/comment' => 'events#comment', :via => :post
  match '/events' => 'events#create', :via => :post, :as => :events
  match '/events/:id' => 'events#show', :as => :event
  match '/tags' => 'static_pages#tags'
  match '/search_results' => 'search#results'
  
  
  match '/quiz/:id' => 'quizzes#quiz', :as => :quiz
  
  root :to => 'static_pages#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @slider_hroniks = Hronik.published.order('created_at DESC').limit(5)
    @elements = (Article.published.all + Hronik.published.all + Old.published.all).sort_by{|e| e[:date]}.reverse
    @elements = @elements.paginate(:page => params[:page], :per_page => 3)
  end
  
  def feedback
    @subscription = Subscription.new
    @feedback = Feedback.new
    @feedbacks = Feedback.published.order('created_at DESC')
  end
  
  def calendar
    @hroniks = Hronik.published.where(:date => params[:date])
    @articles = Article.where(:date => params[:date])
  end
  
  def tags
    @hroniks = Hronik.published.includes(:tags).where("tags.id" => params[:tag_ids]) 
    @articles = Article.includes(:tags).where("tags.id" => params[:tag_ids]) 
    @olds = Old.includes(:tags).where("tags.id" => params[:tag_ids]) 
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_element.html.erb
<div class="span4" style="margin-top: 20px; margin-bottom: 40px;">
	<p><%= Russian::strftime(element.date, "%d %B") %></p>
	<%= link_to truncate(element.title, length: 48), element, :class=> 'hroniki_title_link' %><br>
	<div class="hroniki_tags">
	<% element.tags.all.each do |tag| %>
	  <%= link_to tag.title, tags_path(:tag_ids => tag.id), :class=> 'tag_link' %>
	<% end %>
	</div>
	<div class="hroniki_image_container">
	<div class="hroniki_hover_container" onclick="location.href='<%= url_for(element) %>'">
		<h4 class="title"><%= truncate(element.title, length: 48) %></h4>
		<p style="height: 180px; overflow: hidden;">
		<% text = strip_tags(element.text) %>
		<%= truncate(text, length: 260, omission: '...').html_safe %></p>
		<div class="panel">
			<%= image_tag "hroniki_comment.png" %>
			<span style="margin-right: 10px;"><%= element.comments_qty %></span>
			<%= image_tag "hroniki_watch.png" %>
			<% if element.respond_to?(:session_hroniks) %>
			<%= element.session_hroniks.count %>
			<% elsif element.respond_to?(:article_views) %>
			<%= element.article_views.count %>
			<% elsif element.respond_to?(:old_views) %>
			<%= element.old_views.count %>
			<% end %>
			<%= link_to "читать далее", element %>
		</div>
	</div>
	
	<% if element.class.name == "Hronik" %>
	
	<% if element.from_visitor %>
	<div class="guest_pattern">
	  <% if element.moderated == false %>
	    В процессе модерации
	  <% elsif element.moderated == true %>
	    Читательские хроники
	  <% end %>
	</div>
	<% end %>
	
	<% end %>
	
	<% if element.respond_to?(:cover) %>
	<%= image_tag(element.cover.url(:gallery), :class => "hroniki_image") %>
	<% else %>
	<%= image_tag(element.image.url(:gallery), :class => "hroniki_image") %>
	<% end %>
	</div>
</div>

app/views/static_pages/calendar.html.erb
<div class="container calendar_page" style="margin-top: 200px; margin-bottom: 100px;">
 <div class="row">
   <div class="span9 date_row">
	    <div class="prev_day"><%= link_to "&larr; ".html_safe + Russian::strftime(@date.prev_day, "%d %B"), {date: @date.prev_day}, :class => '' %></div>
	    <span class="current_date"><%= Russian::strftime(@date, "%d %B") %></span>
	    <div class="next_day"><%= link_to date: @date.next_day do %>
	        <%= Russian::strftime(@date.next_day, "%d %B") %> &rarr;
	        <% end %>
	    </div>
	 </div>
	 <div class="span3">
	 </div>
 </div>
 <div class="row">
   <div class="span9">
     <div class="row">
       <%= render partial: "calendar_element", collection: @calendar_elements %>
     </div>
   </div>
	 <%= render 'shared/side' %>
 </div>
</div>

app/views/static_pages/feedback.html.erb
<div class="container" style="margin-top: 200px; margin-bottom: 100px;" id="feedback_page">

  <div class="head_line">
	<p>«Хроники» — это творческий проект компании <%= link_to "Euromed group", "http://euromed-group.ru/", :target => '_blank' %>.</p>
	<p>Главный редактор проекта — <%= mail_to "demmeda@gmail.com", "Дмитрий Журавлёв" %>.</p>
	<p>С предложениями обращайтесь к <%= mail_to "makarenko@euromed.ru", "Марии Макаренко" %>, а ещё мы будем рады вашим отзывам!<p>
  </div>

  <div id="new_feedback_area">
  <%= link_to "Подписка на открытки", "#", :class=> 'show_feedback_form subscribe', :id => 'subscribe_form' %>
  <%= link_to "Оставьте свой отзыв!", "#", :class=> 'show_feedback_form not_active', :id => 'feedback_form' %>
  
  <div class="wrap" id="subscribe_wrap">
  	<%= form_for @subscription, remote: true do |f| %>
  	<div style="float: left;">
  	<label for="subscription_name">Представьтесь, пожалуйста<span class="star">*</span></label>
  	<%= f.text_field :name %>
    <div class="buf" style="height:0px;"></div>
  	Укажите год вашего рождения
  	<%= f.select(:birth, Array(1900..Time.now.year).reverse) %>
    <div class="buf" style="height:20px;"></div>
  	<%= f.label :profession, "Ваша профессия или отрасль, в которой Вы работаете?" %>
  	<%= f.text_field(:profession, :class => 'profession_field') %>
    <div class="buf" style="height:0px;"></div>
  	Ваш индекс<span class="star">*</span>
  	<%= f.text_field(:index, :class => "index_field") %>
  	<span>Вы можете узнать свой индекс на сайте <a href="http://indexp.ru" target="_blank">indexp.ru</a></span>
  	<div class="buf" style="height:0px;"></div>
  	<label for="subscription_address">Ваш адрес<span class="star">*</span></label>
  	<%= f.text_area(:address, :class => "address_field") %>
  	<div class="address_comment">Ваши личные данные будут использованы исключительно для рассылки открыток по почте</div>
  	<div class="buf" style="height:0px;"></div>
  	Ваша электронная почта<span class="star">*</span></label>
  	<%= f.text_field(:email, :class => "email_field") %>
  	<div class="index_comment">Мы оповестим Вас по этому адресу о деталях</div>
  	
  	<label>Подтвердите, что Вы не робот<span class="star">*</span></label></label>
  	
  	<div style="display: inline-block">
  	<%= recaptcha_tags %>
  	</div>
  	
  	<div class="fields_notice"><span class="star">*</span> — этим знаком отмечены поля, <br>обязательные для заполнения</div>
  	
  	<div class="buf" style="height:20px;"></div>
    <div id="subscribe_errors"></div>
  	

  	<%= link_to "Отправить", "#", :class => 'red_button', :id => 'subscription_submit' %>
  	<% end %>
    </div>
  </div>
  
  <div class="wrap" id="feedback_wrap">
	<%= form_for @feedback, remote: true do |f| %>
	<div style="float: left; width: 530px;">
	<%= f.label :name, "Представьтесь, пожалуйста" %>
	<%= f.text_field :name %>
	<%= f.label :feedback, "Добавьте отзыв или предложение" %>
	<%= f.text_area :feedback %>
	<%= f.hidden_field :feedback_type, :value => 'like' %>
	<%= link_to "Можно отправлять", "#", :class => 'red_button', :id => 'feedback_submit' %>
	</div>
	<div style="float: left; margin-left: 150px; width: 220px;">
	<%= link_to "Мне нравится!", "#", :class => 'like_link like active', :id => 'like' %>
	<%= link_to "Не понравилось", "#", :class => 'like_link un_like', :id => 'unlike' %>
	</div>
	<% end %>
  </div>
  </div>

  <h1 style="color: #4c4c4c; margin-top: 60px;">Что о нас думают люди (<%= @feedbacks.count %> <%= Russian.p(@feedbacks.count, "отзыв", "отзыва", "отзывов") %>)</h1>

   <% @feedbacks.each do |feedback| %>
	<div class="feedback">
	<% if feedback.feedback_type == 'like' %>
	<%= image_tag('thumb_up.png')%>
	<% else %>
	<%= image_tag('thumb_down.png')%>
	<% end %>
	<div class="feedback_content">
	  <div class="feedback_heading">
	    <span class="name"><%= feedback.name %></span> | <%= feedback.created_at.strftime("%d.%m.%y") %>
	  </div>
	
	  <div class="feedback_text">
		<p><%= feedback.feedback %></p>
	  </div>
	  
	  <% if feedback.comment? %>
	  <div class="feedback_answer">
		<p style="color: #ff634d;">Наш ответ</p>
		<p><%= feedback.comment %></p>
	  </div>
	  <% end %>
    </div>
	</div>
	
   <% end %>



</div>

<div id="feedback_sent">Спасибо за ваш отзыв!</div>
<div id="subscribtion_created">Вы успешно подписались на рассылку!</div>

app/views/static_pages/index.html.erb
<div class="container">
	
	<div class="row">
	<div class="header-image">
	<div class="slider">
	   	<%= link_to "fwd", "#", :class => 'fwd' %>
		<%= link_to "bck", "#", :class => 'bck' %>
	 <div class="slider2">

     <% @slider_hroniks.each do |hronik| %>
     <div class="slide">
	 	 <div class="slide_img">
		    <%= image_tag hronik.cover.url(:main) %>
		 </div>

	     <div class="span3" style="margin-left: 0px;">
	      <%= link_to "подписка на открытки", feedback_path, :class=> 'ginger_link subscribe' %>
		    <%= link_to "Предложить свой сюжет", "#", :id => 'suggest_hronik', :class=> 'ginger_link feedback_main' %>
		  </div>
	
		 <div class="span8" style="margin-top: 20px; margin-left: 100px;">
			<%= link_to (Russian::strftime(hronik.date, "%d %B") + " " + hronik.title), hronik_path(hronik), :class=> 'title_link' %>
			<p><%= hronik.short %></p>
			<%= link_to "Смотреть", hronik_path(hronik), :class=> 'small_link' %>
		 </div>
	  </div>
	  <% end %>
	  </div>
	  </div>
	  </div>

	  <div class="span12" style="margin-top: 20px;">
	    
		<h3>Что у нас есть нового?</h3>
		
	  </div>
		
		<div id="elements">
			<%= render partial: "element", collection: @elements %>
		</div>
		<%= will_paginate @elements %>
	
	 	
	
	</div>
		
</div>

app/views/static_pages/index.js.erb
$('#elements').append('<%= j render partial: "element", collection: @elements %>');
<% if @elements.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @elements %>');
<% else %>
  $('.pagination').remove();
<% end %>
$(".hroniki_image_container").on("mouseover",function () {
	$(this).find('.hroniki_hover_container').show();
	$(this).find('.hroniki_hover_small_container').show();
});


$(".hroniki_image_container").mouseleave(function () {
	$('.hroniki_hover_container').hide();
	$('.hroniki_hover_small_container').hide();
});

app/views/static_pages/tags.html.erb
<div class="container" style="margin-top: 200px; margin-bottom: 100px;">
 <div class="row">
	<%= render @hroniks %>
 </div>
 <div class="row">
	<%= render @articles %>
 </div>
 <div class="row">
	<%= render @olds %>
 </div>
</div>