config/routes.rb
Hroniki::Application.routes.draw do

  get "subscriptions/create"

  resources :suggests
  resources :hroniks
  match '/hroniks/comment' => 'hroniks#comment', :via => :post

  resources :articles
  match '/articles/comment' => 'articles#comment', :via => :post
  
  match '/olds/issues' => 'olds#issues', :via => :get, :as => :issues
  match '/issues/:id' => 'olds#issue', :as => :issue
  resources :olds
  match '/olds/comment' => 'olds#comment', :via => :post
  
  mount Ckeditor::Engine => '/ckeditor'
  
  match '/feedbacks' => 'feedbacks#create', :via => :post, :as => :feedbacks
  match '/subscriptions' => 'subscriptions#create', :via => :post, :as => :subscriptions
  match '/feedback' => 'static_pages#feedback'
  match '/calendar' => 'events#index'
  match '/events/comment' => 'events#comment', :via => :post
  match '/events' => 'events#create', :via => :post, :as => :events
  match '/events/:id' => 'events#show', :as => :event
  match '/tags' => 'static_pages#tags'
  match '/search_results' => 'search#results'
  
  
  match '/quiz/:id' => 'quizzes#quiz', :as => :quiz
  
  root :to => 'static_pages#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :title, :date, :image
  has_many :olds
  validates :title, :date, :image, presence: true
  
  has_attached_file :image, :styles => { :cover => "220x300#", :ico => "100x100#" }
  
  def self.with_olds
    includes(:olds).where('olds.published = ?', true)
  end
end

app/views/issues/_issue.html.erb
<div class="span12" style="margin-top: 20px; margin-bottom: 40px;">
  <div class="article_image" onclick="location.href='/olds?issue_id=<%= issue.id %>'">
	<%= image_tag(issue.image.url(:cover)) %>
  </div>
  <div class="article_content">
	<p><%= Russian::strftime(issue.date, "%B %Y") %></p>
	<h1 style="color: #4c4c4c;"><%= issue.title %></h1>
	<ul>
	<% issue.olds.each do |old| %>
	<li><%= link_to old.title, old_path(old) %></li>
	<% end %>
	</ul>
	<%= link_to "Скачать весь выпуск (pdf)", issue_path(issue, format: "pdf"), :target => '_blank', :class => 'issue_pdf_link' %>
	
  </div>
</div>