config/routes.rb
Hroniki::Application.routes.draw do

  get "subscriptions/create"

  resources :suggests
  resources :hroniks
  match '/hroniks/comment' => 'hroniks#comment', :via => :post

  resources :articles
  match '/articles/comment' => 'articles#comment', :via => :post
  
  match '/olds/issues' => 'olds#issues', :via => :get, :as => :issues
  match '/issues/:id' => 'olds#issue', :as => :issue
  resources :olds
  match '/olds/comment' => 'olds#comment', :via => :post
  
  mount Ckeditor::Engine => '/ckeditor'
  
  match '/feedbacks' => 'feedbacks#create', :via => :post, :as => :feedbacks
  match '/subscriptions' => 'subscriptions#create', :via => :post, :as => :subscriptions
  match '/feedback' => 'static_pages#feedback'
  match '/calendar' => 'events#index'
  match '/events/comment' => 'events#comment', :via => :post
  match '/events' => 'events#create', :via => :post, :as => :events
  match '/events/:id' => 'events#show', :as => :event
  match '/tags' => 'static_pages#tags'
  match '/search_results' => 'search#results'
  
  
  match '/quiz/:id' => 'quizzes#quiz', :as => :quiz
  
  root :to => 'static_pages#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :date, :image, :text, :title, :tag_ids, :published, :quiz_id,
                  :crop_x, :crop_y, :crop_w, :crop_h
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  default_scope order('date DESC')
  
  has_many :article_tags
  has_many :tags, through: :article_tags
  has_many :article_views
  
  scope :published, -> { where(published: true) }  
  
  validates :date, :text, :title, presence: true
  
  has_attached_file :image, :styles => { 
    :ico => {:geometry => "100x100#", :processors => [:cropper]}, 
    :side => {:geometry => "220x220#", :processors => [:cropper]},
    :gallery => {:geometry => "300x300#", :processors => [:cropper]},
    :show => {:geometry => "640x460>"}
  }
  
  after_update :reprocess_image, :if => :cropping? 
  
  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end
  
  def image_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(image.path(style))
  end
  
  ThinkingSphinx::Index.define :article, :with => :active_record do
    indexes title
    indexes text
  end
  
  
  private
  
  def reprocess_image
    image.assign(image)
    image.save
  end
end

app/models/article_view.rb
class ArticleView < ActiveRecord::Base
  attr_accessible :article_id, :session_id
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.published.order("date DESC").page(params[:page]).per_page(3)
  end

  def show 
    calendar
    @hroniks = Hronik.published.limit(3)
    
    @article = Article.find(params[:id])
    if @article.quiz_id
      @quiz = Quiz.find(@article.quiz_id)
    end
    session_id = request.session_options[:id]
    begin
      ArticleView.create(:article_id => @article.id, :session_id => session_id)
    rescue ActiveRecord::RecordNotUnique
      nil
    end
  end

  def comment
    # api_secret = "GfqyAEOfSrOYwssRtbOk"
    # last_comment = params[:last_comment].encode Encoding::WINDOWS_1251
    # hash = Digest::MD5.hexdigest(api_secret+params[:date]+params[:num]+last_comment)
    # sign = params[:sign]
    # if hash == sign
      @article = Article.find(params[:id])
      @article.comments_qty = params[:num]
      @article.save
    # else
    #   nil
    # end
      render nothing: true
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="span12" style="margin-top: 20px; margin-bottom: 40px;">
  <div class="article_image" onclick="location.href='/articles/<%= article.id %>'">
	<%= image_tag(article.image.url(:side)) %>
  </div>
  <div class="article_content">
	<p><%= Russian::strftime(article.date, "%d %B") %></p>
	<%= link_to article.title, article, :class=> 'hroniki_title_link' %>
	<div class="hroniki_tags">
	<% article.tags.all.each do |tag| %>
	   <%= link_to tag.title, tags_path(:tag_ids => tag.id), :class=> 'tag_link' %>
	<% end %>
	</div>
	<p>
	<% text = strip_tags(article.text).gsub(/&quot;/i,"").gsub(/&nbsp;/i,"") %>
	<%= truncate(text, length: 500, omission: '...').html_safe %></p>
	
	<div class="article_panel">
	<%= image_tag('article_comment.png') %>
	комментариев:
	<span style="margin-right: 20px;"><%= article.comments_qty %></span>
	<%= image_tag('article_watch.png') %>
	просмотров: 
	<span style="margin-right: 10px;"><%= article.article_views.count %></span>
	<%= link_to "читать далее", article %>
	</div>
  </div>
	
</div>

app/views/articles/index.html.erb
<% @title = "Блог" %>
<div class="container" style="margin-top: 200px; margin-bottom: 100px;">
  <h1>Блог</h1>
 <div class="row" id="articles">
	<%= render @articles %>
 </div>
 <%= will_paginate @articles %>
</div>

app/views/articles/index.js.erb
$('#articles').append('<%= j render(@articles) %>');
<% if @articles.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@articles) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/articles/show.html.erb
<% @title = @article.title %>
<% content_for :head do %>
<script src="http://vk.com/js/api/openapi.js" type="text/javascript" charset="windows-1251"></script>
<% end %>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1&appId=171099259748660";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script type="text/javascript">
  VK.init({apiId: 3850211, onlyWidgets: true});
</script>

<script type="text/javascript">
  function addCommentCallback(num, last_comment, date, sign){
    $.post("/articles/comment",{
         type: 'vkontakte',
         num: num,
         last_comment: last_comment,
         date: date,
         sign: sign,
         id: "<%= @article.id %>"
    });
}
</script>


<div class="container" style="margin-top: 200px; margin-bottom: 100px;">
<div class="row">
  <div class="span12">
    <%= link_to articles_path, :class => 'link_to_back' do %>&larr; Назад, к блогу<% end %>
	<div style="margin-top: 20px; margin-bottom: 20px;">
	<h1 style="color: #4c4c4c;"><%= @article.title %></h1>
	<div style="margin-top: 10px;">
	<% @article.tags.each do |tag| %>
	  <%= link_to tag.title, tags_path(:tag_ids => tag.id), :class=> 'tag_link' %>
	<% end %>
	</div>
	</div>
  </div>

  <div class="span9">
	<div class="hronik_cover"><%= image_tag(@article.image.url(:show)) %></div>
    <div class="hronik_text"><%= @article.text.html_safe %></div>
    
    
    <% if @quiz %>
    <h3><%= @quiz.title %></h3>
    <div class="quiz_area">
      <%= form_for @quiz, :url => quiz_path(@quiz), :remote => :true do |f| %>
        
        <ul>
        <% @quiz.answers.each do |a| %>
        <li><%= f.radio_button :answer, a.id %>     <%= a.text %></li>
        <% end %>
        </ul>
        <%= f.submit "Результаты" %>
      <% end %>
    </div>
    
    <div class="quiz_results"></div>
    <% end %>
    
    
    

	<!-- <div class="hronik_social" style="height: 100px;">
	   <p>Понравилась статья? Расскажи друзьям!</p>
	   <div class="like_panel">
	     
	     <div id="vk_like"></div>
	     <script type="text/javascript">
	      VK.Widgets.Like('vk_like', {type: "button"});
	     </script>
	     
	     <a href="https://twitter.com/share" class="twitter-share-button" data-lang="ru">Твитнуть</a>
	     <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
	     
	     <div class="fb-like" data-href="http://hroniki.org/<%= request.fullpath %>" data-width="200" data-layout="button_count" data-show-faces="false" data-send="false"></div>
	     
	     
	   </div>
	 </div>

	 <div id="vk_comments"></div>
	 <script type="text/javascript">
	 VK.Widgets.Comments("vk_comments", {limit: 10, width: "520", attach: "*", onChange: addCommentCallback});
	 </script> -->
	
</div>



<%= render 'shared/side' %>

</div>







</div>




</div>

app/views/articles/show.js.erb
$('#calendar_wrap').html("<%=j render :partial => 'shared/calendar', :@hroniks_by_date => @hroniks_by_date %>");