config/routes.rb
Hroniki::Application.routes.draw do

  get "subscriptions/create"

  resources :suggests
  resources :hroniks
  match '/hroniks/comment' => 'hroniks#comment', :via => :post

  resources :articles
  match '/articles/comment' => 'articles#comment', :via => :post
  
  match '/olds/issues' => 'olds#issues', :via => :get, :as => :issues
  match '/issues/:id' => 'olds#issue', :as => :issue
  resources :olds
  match '/olds/comment' => 'olds#comment', :via => :post
  
  mount Ckeditor::Engine => '/ckeditor'
  
  match '/feedbacks' => 'feedbacks#create', :via => :post, :as => :feedbacks
  match '/subscriptions' => 'subscriptions#create', :via => :post, :as => :subscriptions
  match '/feedback' => 'static_pages#feedback'
  match '/calendar' => 'events#index'
  match '/events/comment' => 'events#comment', :via => :post
  match '/events' => 'events#create', :via => :post, :as => :events
  match '/events/:id' => 'events#show', :as => :event
  match '/tags' => 'static_pages#tags'
  match '/search_results' => 'search#results'
  
  
  match '/quiz/:id' => 'quizzes#quiz', :as => :quiz
  
  root :to => 'static_pages#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/views/shared/_calendar.html.erb
<div id="hroniks">
	  <div id="month">
		<div class="month-inner">
	    <%= link_to "предыдущий месяц", {date: @date.prev_month}, :class => 'prev_month', remote: true %>
	    <div class="current_month">
		<%= Russian::strftime(@date, "%B") %>
		<span style="color: #CCC;"><%= Russian::strftime(@date, "%Y") %></span>
		</div>
	    <%= link_to "следующий месяц", {date: @date.next_month}, :class => 'next_month', remote: true %>
		</div>
	  </div>
  <%= calendar @date do |date| %>
   
    <% if @events_by_date[date] %>
       <%= link_to date.day, calendar_path(:date => date) %>
	  <% else %>
	   <%= date.day %>
    <% end %>
  <% end %>
</div>

app/views/shared/_hronik_suggest.html.erb
<div class="overlay"></div>
<div id="modal">
    
	<div class="modal-header">
		Предложить свой сюжет для «хроник»
		
		<%= link_to "Закрыть", "#", :class => 'close_modal' %>
	</div>
	
	<%= form_for @hronik, remote: true do |f| %>
	<div class="modal-content">
		
		<div class="date" id="date">
		  <div id="number"><%= Russian::strftime(Time.now, "%d") %></div>
		  <div id="month"><%= Russian::strftime(Time.now, "%d %B")[3..-1] %></div>
		</div>
		<div class="suggest-body">
			<%= hidden_field_tag :alt_date %>
			<%= f.hidden_field :date, :value => Time.now %>
			<%= f.text_area :short, :placeholder => "Краткое описание, максимум 70 символов", :class => 'comment' %>
			<%= f.text_field :title, :placeholder => "Заголовок", :class => 'suggest_title' %>
			<%= f.text_area :text, :placeholder => "Добавьте описание", :class => 'suggest_text' %>
			<%= image_tag('suggest-logo-down.png') %>
			<%= f.text_field :author, :placeholder => "и Ваше имя", :class => 'suggest_author' %>
		</div>
		
		<div class="suggest-side">
			<%= image_tag('suggest-logo-top.png') %>
			
			<div class="suggest_file">
			  Прикрепите изображение<br> (jpg, gif, png, не более 3 Мб)
			  <%= f.file_field :cover %>
			</div>
		</div>
		<%= recaptcha_tags %>
		<div id="suggest_errors"></div>
	</div>
	

	
	<% end %>
	
	<%= link_to "Отправить сюжет в редакцию", "#", :class => 'red_button suggest', :id => 'suggest_submit' %>
	
	


</div>

<div id="hronik_sent">
  Спасибо за сюжет, он опубликован. <br> В случае, если сюжет не пройдет модерацию, он будет удален. <br><br>
  <a href="#" id="new_hronik_link">Перейти на страницу вашего сюжета.</a> <br><br>
  <a href="#" class="ok_link">ок</a>
</div>

app/views/shared/_metrika.html.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter22351402 = new Ya.Metrika({id:22351402,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/22351402" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/shared/_side.html.erb
<div class="span3 side">
	<div class="yellow_cation" style="margin-bottom: 20px;">Календарь записей</div>
	<div id="calendar_wrap">
	<%= render 'shared/calendar' %>
	</div>
	<div class="yellow_cation">Что у нас есть нового?</div>
	 <div class="row">
		
     <% @hroniks.each do |hronik| %>
       <div class="span3" style="margin-top: 20px; margin-bottom: 40px;">
			<%= link_to hronik.title, hronik, :class=> 'hroniki_title_link' %><br>
			<% hronik.tags.each do |tag| %>
			  <%= link_to tag.title, tags_path(:tag_ids => tag.id), :class=> 'tag_link' %>
			<% end %>
			<div class="hroniki_image_container">
			<div class="hroniki_hover_small_container" onclick="location.href='/hroniks/<%= hronik.id %>'">
				<p>
				<% text = strip_tags(hronik.text).gsub(/&quot;/i,"").gsub(/&nbsp;/i,"") %>
				<%= truncate(text, length: 170, omission: '...').html_safe %></p>
				<div class="panel">
					<%= link_to "читать далее", hronik %><br>
					<div style="margin-top: 10px;">
					<%= image_tag "hroniki_comment.png" %>
					<span style="margin-right: 20px;"><%= hronik.comments_qty %></span>
					<%= image_tag "hroniki_watch.png" %>
					<%= hronik.session_hroniks.count %>
					</div>
				</div>
			</div>
			<%= image_tag(hronik.cover.url(:side), :class => "hroniki_image") %>
			</div>
		</div>
	   <% end %>
	</div>
</div>